openapi: 3.0.3
info:
  title: DrPlantes Authentication API
  description: Authentication and user management endpoints for the Plant Management MVP
  version: 1.0.0
  contact:
    name: DrPlantes Team

servers:
  - url: http://localhost:3000/api/v1
    description: Local development
  - url: https://api.drplantes.com/api/v1
    description: Production

tags:
  - name: Authentication
    description: User registration, login, and password management
  - name: User Profile
    description: User profile and account management

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user account
      description: Creates a new user account with email and password. Default role is 'end_user'.
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login with email and password
      description: Authenticates user and returns JWT token
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          $ref: '#/components/responses/ValidationError'

  /auth/reset-password:
    post:
      tags:
        - Authentication
      summary: Request password reset
      description: Sends password reset email to user
      operationId: requestPasswordReset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '200':
          description: Reset email sent (always returns 200 for security)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: If the email exists, a reset link has been sent
        '400':
          $ref: '#/components/responses/ValidationError'

  /auth/reset-password/confirm:
    post:
      tags:
        - Authentication
      summary: Confirm password reset with token
      description: Resets password using token from email
      operationId: confirmPasswordReset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  description: Reset token from email
                newPassword:
                  type: string
                  format: password
                  minLength: 8
                  example: newSecurePassword123
      responses:
        '200':
          description: Password successfully reset
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password successfully reset
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/me:
    get:
      tags:
        - User Profile
      summary: Get current user profile
      description: Returns the authenticated user's profile information
      operationId: getCurrentUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      tags:
        - User Profile
      summary: Update current user profile
      description: Updates the authenticated user's profile (name, email, password)
      operationId: updateCurrentUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Profile successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Email already in use
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - User Profile
      summary: Delete user account
      description: Soft deletes the authenticated user's account and all associated data
      operationId: deleteCurrentUser
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Account successfully deleted
        '401':
          $ref: '#/components/responses/Unauthorized'

  /users/me/export:
    get:
      tags:
        - User Profile
      summary: Export user data
      description: Returns all user data in JSON format (GDPR compliance)
      operationId: exportUserData
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User data export
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDataExport'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
        - displayName
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: securePassword123
        displayName:
          type: string
          minLength: 1
          maxLength: 100
          example: John Doe

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: securePassword123

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        user:
          $ref: '#/components/schemas/UserProfile'

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        email:
          type: string
          format: email
          example: user@example.com
        displayName:
          type: string
          example: John Doe
        role:
          type: string
          enum: [end_user, expert, admin]
          example: end_user
        createdAt:
          type: string
          format: date-time
          example: 2025-12-07T10:00:00.000Z
        updatedAt:
          type: string
          format: date-time
          example: 2025-12-07T10:00:00.000Z

    UpdateUserRequest:
      type: object
      properties:
        displayName:
          type: string
          minLength: 1
          maxLength: 100
          example: Jane Doe
        email:
          type: string
          format: email
          example: newemail@example.com
        currentPassword:
          type: string
          format: password
          description: Required if changing email or password
        newPassword:
          type: string
          format: password
          minLength: 8
          description: New password (requires currentPassword)

    UserDataExport:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserProfile'
        plants:
          type: array
          items:
            type: object
            description: User's plant data
        wateringEvents:
          type: array
          items:
            type: object
            description: User's watering history
        exportedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        message:
          type: string
          example: Validation failed
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: email
              message:
                type: string
                example: Invalid email format
        timestamp:
          type: string
          format: date-time
        path:
          type: string
          example: /api/v1/auth/register

  responses:
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized - Invalid or missing JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            statusCode: 401
            message: Unauthorized
            timestamp: 2025-12-07T10:00:00.000Z
            path: /api/v1/users/me
